#!/usr/bin/env bash
set -euo pipefail

export CGO_ENABLED=0
pushd "$(dirname "$0")/.." >/dev/null

PKGS=$(go list "." ./grpc | sed 's|github.com/pingcap/dbaas/||')
echo checking packages: $PKGS
pushd tools
./install.sh
popd

# Some linters only work if code is vendored
GO111MODULE=on go mod vendor

echo "linting"
./tools/bin/revive -formatter friendly -config conf/revive.toml ${PKGS}

echo "checking"
# golangci has a bug when given file arguments
./tools/bin/golangci-lint run
